name: dart_valkey
description: Dart client for Valkey (and Redis-compatible servers)
version: 0.0.4

repository: https://github.com/coolosos/dart-valkey
issue_tracker: https://github.com/coolosos/dart-valkey/issues
homepage: https://github.com/coolosos
topics:
  - valkey
  - redis
  - database
  - client
  - pubsub

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.17.0
dev_dependencies:
  mockito: ^5.5.0
  build_runner: ^2.7.0
  test: ^1.19.2
  coolint: ^2.1.2
  coverage: ^1.15.0
